services:
  - type: web
    name: makeup-store-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

